language: rust
dist: trusty
sudo: false
rust:
  - nightly
  - beta
  - stable
  - 1.20.0
cache:
  directoriesca:
    - target/debug/deps
    - target/debug/build
script:
  - cargo build --verbose
  - cargo test --verbose
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo bench --verbose
    fi
