language: rust
dist: trusty
sudo: false
rust:
  - nightly
  - beta
  - stable
  - 1.20.0
cache:
  directoriesca:
    - target/debug/deps
    - target/debug/build
script:
  - cargo build --verbose
  - cargo test --verbose
after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo bench --verbose;
    fi
  - |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    LOCAL="~/.local" && export PATH=$LOCAL/bin:$PATH &&
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz &&
    cd kcov-master &&
    mkdir build &&
    cd build &&
    cmake .. &&
    make &&
    make install DESTDIR=../../kcov-build &&
    cd ../.. &&
    rm -rf kcov-master &&
    for file in target/debug/thhp-*[^\.d]; do
      mkdir -p "target/cov/$(basename $file)";
      ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file";
    done &&
    bash <(curl -s https://codecov.io/bash) &&
    echo "Uploaded code coverage"
