[package]
name = "thhp"
version = "0.1.0"
authors = ["kei10in <kei10in@gmail.com>"]

[dependencies]
error-chain = "0.11"

[dev-dependencies]
httparse = "1.2"
picohttpparser-sys = { git = "https://github.com/kevinswiber/picohttpparser-sys" }

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3

[features]
nightly = [ "picohttpparser-sys/sse4" ]
