[package]
name = "httpparser"
version = "0.1.0"
authors = ["kei10in <kei10in@gmail.com>"]

[dependencies]
error-chain = "0.11"

[dev-dependencies]
httparse = "1.2"
pico-sys = "0.0"

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3
